### ISSUE TITLE
Issue with gettid

### ISSUE THREAD

**Issue by rralf** [igaw/jitterdebugger#16]
With a recent gcc compiler on an Arch distribution, jitterdebugger fails to compile with
```
jitterdebugger.c:150:14: error: static declaration of ‘gettid’ follows non-static declaration
  150 | static pid_t gettid(void)
      |              ^~~~~~
In file included from /usr/include/unistd.h:1170,
                 from jitterdebugger.c:6:
/usr/include/bits/unistd_ext.h:34:16: note: previous declaration of ‘gettid’ was here
   34 | extern __pid_t gettid (void) __THROW;
```

Why do you implement your own gettid? On one of our systems, gettid comes with sys/types.h. I guess we should either use the system's implementation, or annotate jitterdebugger's gettid.

Thanks
  Ralf

**Comment by igaw** [comment]
The Linux gettid() call was for a long time not supported by glibc.

https://sourceware.org/bugzilla/show_bug.cgi?id=6399

I assume the Arch distro ships with a very recent version of glibc which now has the support for gettid(). Since this is a transition period we just can't drop it immediately from our code base.  I suppose something like

`#ifndef gettid
statid pid_t gettid(void)....
#endif
`
could be added. Care to send a patch?

**Comment by rralf** [comment]
Will send a patch tomorrow.

**Comment by rralf** [comment]
Hm. I don't see how the preprocessor could solve this as it doesn't see function names.

What do you think of this? https://github.com/lfd/jitterdebugger/commit/c3da12ac9bb893ec6e9d92c73d79509a3632d493

**Comment by igaw** [comment]
Good point. CPP is soooo bad. Let's go with your idea to avoid the problem.

**Comment by rralf** [comment]
See #17

**Comment by igaw** [comment]
Patch applied. Thanks.
